apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apigokafka
  name: apigokafka
  namespace: usactar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigokafka
  template:
    metadata:
      labels:
        app: apigokafka
    spec:
      containers:
      - image: esdrastochi/gokafka_201807373
        imagePullPolicy: Always
        name: apigokafka
        ports:
          - containerPort: 3030
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: apigokafka
  name: apigokafka
  namespace: usactar
spec:
  ports:
  - port: 3030
    protocol: TCP
    targetPort: 3030
  selector:
    app: apigokafka
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: usactar
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /input
spec:
  ingressClassName: nginx
  rules:
    - host: "34.70.59.65.nip.io"
      http:
        paths:
          - backend:
              service:
                name: apigokafka
                port: 
                  number: 3030
            path: /input
            pathType: Prefix